# Generated by Django 5.1.2 on 2024-10-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['symbol', 'date'], name='api_stockpr_symbol_a3e398_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together={('symbol', 'date')},
        ),
    ]
